services:
  seafile:
    image: seafileltd/seafile-pro-mc:12.0-latest
    environment:
      - DB_HOST=${SEAFILE_MYSQL_DB_HOST:-db}
      - DB_PASSWORD=${SEAFILE_MYSQL_DB_PASSWORD:?Variable is not set or empty}
      - DB_PORT=${SEAFILE_MYSQL_DB_PORT:-3306}
      - DB_ROOT_PASSWD=${INIT_SEAFILE_MYSQL_ROOT_PASSWORD:-}
      - DB_USER=${SEAFILE_MYSQL_DB_USER:-seafile}
      - ENABLE_SEADOC=false
      - INIT_SEAFILE_ADMIN_EMAIL=${INIT_SEAFILE_ADMIN_EMAIL:-me@example.com}
      - INIT_SEAFILE_ADMIN_PASSWORD=${INIT_SEAFILE_ADMIN_PASSWORD:-asecret}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY:?Variable is not set or empty}
      - NON_ROOT=false
      - SEADOC_SERVER_URL=https://${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}/sdoc-server
      - SEAFILE_LOG_TO_STDOUT=${SEAFILE_LOG_TO_STDOUT:-false}
      - SEAFILE_MYSQL_DB_CCNET_DB_NAME=${SEAFILE_MYSQL_DB_CCNET_DB_NAME:-ccnet_db}
      - SEAFILE_MYSQL_DB_SEAFILE_DB_NAME=${SEAFILE_MYSQL_DB_SEAFILE_DB_NAME:-seafile_db}
      - SEAFILE_MYSQL_DB_SEAHUB_DB_NAME=${SEAFILE_MYSQL_DB_SEAHUB_DB_NAME:-seahub_db}
      - SEAFILE_SERVER_HOSTNAME=${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}
      - SEAFILE_SERVER_PROTOCOL=${SEAFILE_SERVER_PROTOCOL:-https}
      - SITE_ROOT=${SITE_ROOT:-/}
      - TIME_ZONE=${TIME_ZONE:-Etc/UTC}
      - FORCE_HTTPS_IN_CONF=true
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_started
      elasticsearch:
        condition: service_started
    healthcheck:
      test:
        - CMD
        - curl
        - http://localhost/api2/ping/
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - /data/seafile:/shared

  elasticsearch:
    image: elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    healthcheck:
      test:
        - CMD
        - curl
        - http://localhost:9200
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      default:
        aliases:
          - elasticsearch
    volumes:  
      - /data/seasearch:/usr/share/elasticsearch/data 

  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${INIT_SEAFILE_MYSQL_ROOT_PASSWORD:-}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--connect",
          "--mariadbupgrade",
          "--innodb_initialized",
        ]
      interval: 30s
      start_period: 30s
      timeout: 5s
      retries: 10
    networks:
      default:
        aliases:
          - db
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
    volumes:
      - "seafile-mysql:/var/lib/mysql"

  memcached:
    image: memcached:1.6.29
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      default:
        aliases:
          - memcached
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
    healthcheck:
      test:
        - CMD
        - memcached
        - --version
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  seafile-mysql:
