services:
  seafile:
    image: seafileltd/seafile-pro-mc:12.0-latest
    environment:
      - DB_HOST=${SEAFILE_MYSQL_DB_HOST:-db}
      - DB_PASSWORD=${SEAFILE_MYSQL_DB_PASSWORD:?Variable is not set or empty}
      - DB_PORT=${SEAFILE_MYSQL_DB_PORT:-3306}
      - DB_ROOT_PASSWD=${INIT_SEAFILE_MYSQL_ROOT_PASSWORD:-}
      - DB_USER=${SEAFILE_MYSQL_DB_USER:-seafile}
      - ENABLE_SEADOC=false
      - INIT_SEAFILE_ADMIN_EMAIL=${INIT_SEAFILE_ADMIN_EMAIL:-me@example.com}
      - INIT_SEAFILE_ADMIN_PASSWORD=${INIT_SEAFILE_ADMIN_PASSWORD:-asecret}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY:?Variable is not set or empty}
      - NON_ROOT=false
      - SEADOC_SERVER_URL=https://${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}/sdoc-server
      - SEAFILE_LOG_TO_STDOUT=${SEAFILE_LOG_TO_STDOUT:-false}
      - SEAFILE_MYSQL_DB_CCNET_DB_NAME=${SEAFILE_MYSQL_DB_CCNET_DB_NAME:-ccnet_db}
      - SEAFILE_MYSQL_DB_SEAFILE_DB_NAME=${SEAFILE_MYSQL_DB_SEAFILE_DB_NAME:-seafile_db}
      - SEAFILE_MYSQL_DB_SEAHUB_DB_NAME=${SEAFILE_MYSQL_DB_SEAHUB_DB_NAME:-seahub_db}
      - SEAFILE_SERVER_HOSTNAME=${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}
      - SEAFILE_SERVER_PROTOCOL=${SEAFILE_SERVER_PROTOCOL:-https}
      - SITE_ROOT=${SITE_ROOT:-/}
      - TIME_ZONE=${TIME_ZONE:-Etc/UTC}
      - FORCE_HTTPS_IN_CONF=true
    depends_on:
      db:
        condition: service_healthy
      memcached:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - http://localhost/api2/ping/
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    volumes:
      - /data/seafile:/shared

  collabora:
    image: collabora/code:24.04.5.1.1
    expose:
      - 9980
    cap_add:
      - MKNOD
    environment:
      - server_name=${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}:${COLLABORA_PORT:-6232}
      - username=${COLLABORA_USERNAME:?Variable is not set or empty}
      - password=${COLLABORA_PASSWORD:?Variable is not set or empty}
      - DONT_GEN_SSL_CERT=true
      - TZ=${TIME_ZONE:-Europe/Berlin}
      - extra_params=--o:admin_console.enable=${COLLABORA_ENABLE_ADMIN_CONSOLE:-true}
        --o:ssl.enable=false
        --o:ssl.termination=true
        --o:user_interface.mode=classic
        --o:remote_font_config.url=${COLLABORA_REMOTE_FONT:-}
        --o:logging.file[@enable]=${COLLABORA_ENABLE_FILE_LOGGING:-false}
        --o:logging.file.property[0]=/opt/cool/logs/coolwsd.log
    labels:
      - 'caddy.reverse_proxy={{upstreams 9980}}'
    healthcheck:
      test:
        - CMD
        - curl
        - http://localhost:6232
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      default:
        aliases:
          - collabora
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    healthcheck:
      test:
        - CMD
        - curl
        - http://localhost:9200
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      default:
        aliases:
          - elasticsearch
    restart: unless-stopped
    volumes:  
      - seafile-elasticsearch:/usr/share/elasticsearch

  db:
    image: mariadb:10.11
    environment:
      - MYSQL_ROOT_PASSWORD=${INIT_SEAFILE_MYSQL_ROOT_PASSWORD:-}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--connect",
          "--mariadbupgrade",
          "--innodb_initialized",
        ]
      interval: 10s
      start_period: 10s
      timeout: 5s
      retries: 10
    networks:
      default:
        aliases:
          - db
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
    restart: unless-stopped
    volumes:
      - "seafile-mysql:/var/lib/mysql"

  memcached:
    image: memcached:1.6.29
    entrypoint: memcached -m 256
    networks:
      default:
        aliases:
          - memcached
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - memcached
        - --version
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  seafile-mysql:
  seafile-elasticsearch:
